// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu6ELsffiqalt1BQxLEwE23smmKjbKGUg',
    appId: '1:1323354876:web:82e082d65db08998d32579',
    messagingSenderId: '1323354876',
    projectId: 'phonebook-994d6',
    authDomain: 'phonebook-994d6.firebaseapp.com',
    storageBucket: 'phonebook-994d6.appspot.com',
    measurementId: 'G-NLVCCTW74P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAchuX2sOjwdqwo5EAx-Wx7Tuuf6N_mOCk',
    appId: '1:1323354876:android:913c60f266b0c9dcd32579',
    messagingSenderId: '1323354876',
    projectId: 'phonebook-994d6',
    storageBucket: 'phonebook-994d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU_ut9ox7YYqA_0iR5nNRFdOJgl6jvp7M',
    appId: '1:1323354876:ios:872e4d6b074c9583d32579',
    messagingSenderId: '1323354876',
    projectId: 'phonebook-994d6',
    storageBucket: 'phonebook-994d6.appspot.com',
    iosClientId: '1323354876-aejjh5sir8r0h430sjii8os971iade14.apps.googleusercontent.com',
    iosBundleId: 'com.example.phonebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU_ut9ox7YYqA_0iR5nNRFdOJgl6jvp7M',
    appId: '1:1323354876:ios:872e4d6b074c9583d32579',
    messagingSenderId: '1323354876',
    projectId: 'phonebook-994d6',
    storageBucket: 'phonebook-994d6.appspot.com',
    iosClientId: '1323354876-aejjh5sir8r0h430sjii8os971iade14.apps.googleusercontent.com',
    iosBundleId: 'com.example.phonebook',
  );
}
